var context = {
  "Math": ["PI", "abs", "acos", "asin", "atan", "ceil", "cos", "exp", "floor", "max", "min", "pow", "random", "round", "sin", "sqrt", "tan"],
  "location": ["hash", "host", "hostname", "href", "origin", "pathname", "port", "reload", "replace", "search"],
  "navigator": ["appCodeName", "appName", "appVersion", "cookieEnabled", "doNotTrack", "geolocation", "getGamepads", "getStorageUpdates", "javaEnabled", "language", "maxTouchPoints", "mimeTypes", "onLine", "platform", "plugins", "product", "productSub", "registerProtocolHandler", "userAgent", "vendor", "vendorSub", "vibrate", "webkitGetGamepads", "webkitGetUserMedia", "webkitPersistentStorage", "webkitTemporaryStorage"],
  "localStorage": ["clear", "getItem", "key"],
  "JSON": ["parse", "stringify"],
  "Object": ["getPrototypeOf", "getOwnPropertyDescriptor", "getOwnPropertyNames", "create", "defineProperty", "defineProperties", "seal", "freeze", "preventExtensions", "isSealed", "isFrozen", "isExtensible", "keys"],
  "console": ["assert", "clear", "count", "debug", "dir", "dirxml", "error", "group", "groupCollapsed", "groupEnd", "info", "log", "markTimeline", "memory", "profile", "profileEnd", "table", "time", "timeEnd", "timeStamp", "timeline", "timelineEnd", "trace", "warn"],
  "window": ["PERSISTENT", "TEMPORARY", "addEventListener", "alert", "applicationCache", "atob", "blur", "btoa", "caches", "cancelAnimationFrame", "cancelIdleCallback", "captureEvents", "chrome", "clearInterval", "clearTimeout", "clientInformation", "close", "closed", "confirm", "console", "createImageBitmap", "crypto", "customElements", "defaultStatus", "defaultstatus", "devicePixelRatio", "dispatchEvent", "document", "external", "fetch", "find", "focus", "frameElement", "frames", "getComputedStyle", "getMatchedCSSRules", "getSelection", "history", "indexedDB", "innerHeight", "innerWidth", "isSecureContext", "length", "localStorage", "location", "locationbar", "matchMedia", "menubar", "moveBy", "moveTo", "name", "navigator", "onabort", "onanimationend", "onanimationiteration", "onanimationstart", "onauxclick", "onbeforeunload", "onblur", "oncancel", "oncanplay", "oncanplaythrough", "onchange", "onclick", "onclose", "oncontextmenu", "oncuechange", "ondblclick", "ondevicemotion", "ondeviceorientation", "ondeviceorientationabsolute", "ondrag", "ondragend", "ondragenter", "ondragleave", "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onerror", "onfocus", "ongotpointercapture", "onhashchange", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onlanguagechange", "onload", "onloadeddata", "onloadedmetadata", "onloadstart", "onlostpointercapture", "onmessage", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onmousewheel", "onoffline", "ononline", "onpagehide", "onpageshow", "onpause", "onplay", "onplaying", "onpointercancel", "onpointerdown", "onpointerenter", "onpointerleave", "onpointermove", "onpointerout", "onpointerover", "onpointerup", "onpopstate", "onprogress", "onratechange", "onrejectionhandled", "onreset", "onresize", "onscroll", "onsearch", "onseeked", "onseeking", "onselect", "onshow", "onstalled", "onstorage", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle", "ontransitionend", "onunhandledrejection", "onunload", "onvolumechange", "onwaiting", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart", "onwebkittransitionend", "onwheel", "open", "openDatabase", "opener", "origin", "outerHeight", "outerWidth", "pageXOffset", "pageYOffset", "parent", "performance", "personalbar", "postMessage", "print", "prompt", "releaseEvents", "removeEventListener", "requestAnimationFrame", "requestIdleCallback", "resizeBy", "resizeTo", "screen", "screenLeft", "screenTop", "screenX", "screenY", "scroll", "scrollBy", "scrollTo", "scrollX", "scrollY", "scrollbars", "self", "sessionStorage", "setInterval", "setTimeout", "speechSynthesis", "status", "statusbar", "stop", "styleMedia", "toolbar", "top", "webkitCancelAnimationFrame", "webkitRequestAnimationFrame", "webkitRequestFileSystem", "webkitResolveLocalFileSystemURL", "webkitStorageInfo"]
}
var variables = [
  "Date", "getDate", "getDay", "getFullYear", "getHours", "getMilliseconds", "getMinutes", "getMonth", "getSeconds", "getTime", "getYear",
  "String", "toString", "toLowerCase", "toUpperCase", "charAt", "concat", "indexOf", "lastIndexOf", "match", "slice", "split", "substr", "substring", "trim", "valueOf",
  "Array", "isArray", "indexOf", "lastIndexOf", "every", "some", "forEach", "map", "filter", "reduce", "reduceRight",
  "require"
]

module.exports = {
  variables: variables,
  context: context
}